// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaJAboccObOlqWL1mo8aXHfqk5v3ppzxU',
    appId: '1:383600826599:web:b4d24abb3fbe8c9774aa42',
    messagingSenderId: '383600826599',
    projectId: 'flow-project-343a3',
    authDomain: 'flow-project-343a3.firebaseapp.com',
    storageBucket: 'flow-project-343a3.firebasestorage.app',
    measurementId: 'G-61SRG1B2ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcOFHMB-RBRcdm2wEk19naEyDBXIN4MXE',
    appId: '1:383600826599:android:5f61bdc9540d9e1674aa42',
    messagingSenderId: '383600826599',
    projectId: 'flow-project-343a3',
    storageBucket: 'flow-project-343a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM47kpasnyuYqiw_bS2lqf3Ygn6ozudeY',
    appId: '1:383600826599:ios:3872cce4095a7a0674aa42',
    messagingSenderId: '383600826599',
    projectId: 'flow-project-343a3',
    storageBucket: 'flow-project-343a3.firebasestorage.app',
    iosBundleId: 'com.example.flowProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM47kpasnyuYqiw_bS2lqf3Ygn6ozudeY',
    appId: '1:383600826599:ios:3872cce4095a7a0674aa42',
    messagingSenderId: '383600826599',
    projectId: 'flow-project-343a3',
    storageBucket: 'flow-project-343a3.firebasestorage.app',
    iosBundleId: 'com.example.flowProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaJAboccObOlqWL1mo8aXHfqk5v3ppzxU',
    appId: '1:383600826599:web:8376d21a5001277074aa42',
    messagingSenderId: '383600826599',
    projectId: 'flow-project-343a3',
    authDomain: 'flow-project-343a3.firebaseapp.com',
    storageBucket: 'flow-project-343a3.firebasestorage.app',
    measurementId: 'G-1KSQDG8DS3',
  );
}
